### ISSUE TITLE
Add New Team Issue

### ISSUE THREAD

**Issue by heymonicakay** [NSS-Day-Cohort-42/trunch-bunch-truncheons-and-flagons#28]
### Description of Issue
> On page load, teams data is rendered to the DOM as Leaderboard content. When a new team is created, that Leaderboard content is erroneously appended with the updated teams data, resulting in duplicate teams being displayed.

### Steps To Recreate Issue:
1. Serve to browser
1. Enter team into `Enter Team Name` field 
1. Click `Create Team`

### Expected Outcome: 
> A new teamObject is added to the teams database, and then the updated teamsList is rendered to the teamSelect dropdown list. _Not expecting any changes to the Leaderboard content._

### Observed Behavior:
> The Leaderboard content is appended with an additional teamsList from teams database. Repeatable with each new team created.

**Comment by mgjeffries** [comment]
Issue resolved in recent PR.
